[client]
server-address = "127.0.0.1:6142"
field-of-view = 68.0

[key-map]
move-forward = 17
move-backward = 31
move-left = 30
move-right = 32
move-up = 57

[logging]
level = "Debug"
file = "client.log"

[mouse]
sensitivity = 3.15

[simulation]
movement-speed = 6.0
jump-force = 10.35

[simulation.physics]
gravity = 0.48
